[mode]
# mode: generate new data file or plot data from an existing data file
    # generate - generate new data file
    # plot - plot the data from a data fie
mode = 'plot'

# LOGGER SETTINGS
[logger]
# level: the level of details to be included in the log
    # ERROR, INFO, DEBUG
level = 'DEBUG'


[files]
# data_file_name: name of the data file to be used for plotting
data_file_name = 'composites.db'


# NUMBER SET PARAMETERS
[set]
# mode of number generation
# options: family, range
mode = 'range'

# family mode: generates a number of families; each family is based on a family product and a number of identity factors
# list of families to be generated
families = [[2, 293]]

# identity factor iteration mode: range or count
# count: the number of identity factors in each family (determines the family size)
identity_factor_mode = 'range'

# range: the identity factors in a family are between identity_factor_range_min and identity_factor_range_max
identity_factor_range_min = 2
identity_factor_range_max = 200000

# type of identity factor minimum
# options: origin, family, value
# origin: first identity factor is 2
# family: first identity factor is the lowest prime smaller than the largest family factor []
# value: first family factor is the lowest prime above a specific value
identity_factor_minimum_mode = 'family'

# the value of the first identity factor if identity_factor_minimum_mode is set to 'value'
identity_factor_minimum_value = 2

# identity factor count: the number of identity factors in a family
identity_factor_count = 1000

# range mode: generates a range of consecutive numbers
# whether prime numbers should be included in the range or skipped
include_primes = false

# range minimum and maximum: first and last numbers to be included in the range
range_min = 2
range_max = 10000

ignore_missing_plot_values = true

# PLOT PARAMETERS
[plot]
width = 1600
height = 900
point_size = 2

# value to be visualized on the Y-axis
# options: mean_deviation, antislope, ideal_factor
mode = 'mean_deviation'

# whether the numbers should be colored by slope buckets
# options: true, false
use_color_buckets = true

# bokeh palette to be used if use_color_buckets is set to true
# options: Magma, Inferno, Plasma, Viridis, Cividis, Turbo, Default
# Default = Turbo
# preview: https://docs.bokeh.org/en/latest/docs/reference/palettes.html
palette = 'Turbo'

# palette_range: maximum number of colors to be used
    # limited by the palette
    # https://docs.bokeh.org/en/latest/docs/reference/palettes.html
palette_range = 11

# colorization_value: number attribute to be used for colorization
    # value
    # ideal factor
    # mean deviation
    # anti slope
    # division family
colorization_value = 'division family'

# use rounding of property used for bucket assignment
# options: full, up, down
property_rounding = 'full'