[mode]
# mode: generate new data file or plot data from an existing data file
    # generate - generate new data file
    # plot - plot the data from a data fie
mode = 'generate'
check_data = true

# LOGGER SETTINGS
[logger]
# level: the level of details to be included in the log
    # ERROR, INFO, DEBUG
level = 'DEBUG'


[files]
# data_file_name: name of the data file to be used for plotting
data_file_name = 'composites.db'

# reset_output_data: whether the output folder should be emptied before stashing the new html file
reset_output_data = false


# NUMBER SET PARAMETERS
[set]
# mode of number generation
# options: family, range
mode = 'range'

# family mode: generates a number of families; each family is based on a family product and a number of identity factors
# list of families to be generated
families = [[2, 2, 7], [3, 5, 11], [11, 13, 17]]

# identity factor iteration mode: range or count
# count: the number of identity factors in each family (determines the family size)
identity_factor_mode = 'count'

# range: the identity factors in a family are between identity_factor_range_min and identity_factor_range_max
identity_factor_range_min = 2
identity_factor_range_max = 1000

# type of identity factor minimum
# options: origin, family, value
# origin: first identity factor is 2
# family: first identity factor is the lowest prime smaller than the largest family factor []
# value: first family factor is the lowest prime above a specific value
identity_factor_minimum_mode = 'family'

# the value of the first identity factor if identity_factor_minimum_mode is set to 'value'
identity_factor_minimum_value = 2

# identity factor count: the number of identity factors in a family
identity_factor_count = 10000

# range mode: generates a range of consecutive numbers
# whether prime numbers should be included in the range or skipped
include_primes = false

# range minimum and maximum: first and last numbers to be included in the range
range_min = 2
range_max = 110


# GRAPH PARAMETERS
[graph]
width = 1600
height = 900
point_size = 5

# value to be visualized on the Y-axis
# options: mean_deviation, antislope, ideal_factor
mode = 'mean_deviation'

# whether the numbers should be colored by slope buckets
# options: true, false
use_color_buckets = true

# bokeh palette to be used if use_color_buckets is set to true
# options: Magma, Inferno, Plasma, Viridis, Cividis, Turbo, Default
# Default = Turbo
# preview: https://docs.bokeh.org/en/latest/docs/reference/palettes.html
palette = 'Default'


# RUN PARAMETERS
[run]
# create a csv file with the generated number data
create_csv = true

# information included in the timestamp of the 'hard copy' file name (for the same number range)
# .. affects the number of files produced when multiple consecutive runs are made
# .. ex. date will re-write one file during the day
# .. full will create new file for each run
# options:
# 0 = date only - day month year
# 1 = down to hour information, day month year hour
# 2 = down to minute information, day month year hour minute
# 3 = full timestamp, day month year hour minute second
hard_copy_timestamp_granularity = 0

# if true, the files in the output folder will be removed before each run
# options: true, false
reset_output_data = false